package com.shinom.blogging.helper;

public enum AuthStatus {
	
	USER_CREATED_SUCCESSFULLY,
	USER_NOT_CREATED,
	ACCOUNT_ALREADY_EXIST, 
	LOGIN_SUCCESS, 
	LOGIN_FAILED,
	OTP_SENT_SUCCESSFULLY,
	EMAIL_REGISTERED_WITH_ANOTHER_ACCOUNT, 
	EMAIL_NOT_REGISTERED,
	PASSWORD_CHANGED_SUCCESSFULLY,
	FAILED_TO_SEND_OTP
}
